#!/usr/bin/sh
source /home/artic/.config/appid
cat <<EOF
[ \
    { \
        "application_id": $id, \
        "state": "λ ", \
    "details": "artic@arco | ~", \
        "large_image": { \
            "key": "https://cdn.discordapp.com/emojis/842958943269683242.gif?size=96&quality=lossless", \
            "text": "despair" \
        }, \
        "small_image": null, \
        "start_timestamp": null, \
        "end_timestamp": null, \
        "buttons": [ \
       { \
                "label": ".dotfiles", \
                "url": "https://github.com/ArticExploit/dotfiles" \
            }, \
       { \
                "label": "PGP and SSH keys", \
                "url": "https://media.articexploit.xyz:8443/keys/" \
            } \
        ] \
    } \
]
EOF
