#!/usr/bin/sh
source /home/artic/.config/appid
cat <<EOF
[ \
    { \
        "application_id": $id, \
        "state": "uptime: 21y", \
    "details": "os: Soul", \
        "large_image": { \
            "key": "https://cdn.discordapp.com/emojis/1038755084454068244.gif", \
            "text": "Look at that subtle solarized coloring. The tasteful contrast of it. Oh my God, it even has neofetch..." \
        }, \
        "small_image": null, \
        "start_timestamp": null, \
        "end_timestamp": null, \
        "buttons": [ \
       { \
                "label": ".dotfiles", \
                "url": "https://github.com/ArticExploit/dotfiles" \
            }, \
       { \
                "label": "PGP and SSH keys", \
                "url": "https://media.articexploit.xyz:8443/keys/" \
            } \
        ] \
    } \
]
EOF
